[project]
name = "pt-blog"
version = "0.1.0"
description = "Add a short description here"
authors = ["Arturo Trujillo <alebrijedev@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
nodejs = "20.8.1.*"
